import { AnimatedStat } from "@/components/marketing/AnimatedStat";
import { HostsTile } from "@/components/marketing/HostsTile";
import { EpisodeExpandMark } from "@/components/marketing/EpisodeExpandMark";
import { BlindSpotGrid } from "@/components/marketing/BlindSpotGrid";
import { getEpisodeStats, getAllHosts, getAllEpisodes } from "@/lib/content";

/**
 * Proof-by-numbers bento: one tall slate tile carrying the headline stat,
 * plus a 2×2 of light tiles that each pair a brand mark with a caption.
 *
 * Every number derives from the catalog at build time (count / host count /
 * first and last year) — never hardcoded, never fabricated. The captions reuse
 * copy already sanctioned in the hero micro-labels.
 *
 * The slate tile is type only, and so is the convening tile: its years-running
 * figure is the same `AnimatedStat` count-up as the headline stat, so the two
 * numbers on the grid behave alike. The remaining two carry a mark and each owns
 * its own tile so it can gate its motion on hover: `HostsTile` (chips that roll)
 * and `EpisodeExpandMark` (an accordion of real episodes). The blind-spots tile
 * is a still `ink/` mark from the brand asset library (`design/assets/`,
 * generated by `design/build-assets.py` — edit the script, not the SVG), served
 * `unoptimized` so Next passes it through as authored.
 */

const tileClass =
  "bento-cell relative flex min-h-[372px] flex-col items-center rounded-2xl border border-line bg-linear-to-b from-accent-50 to-accent-100 p-9 text-center";

export function StatBento() {
  const stats = getEpisodeStats();
  const hosts = getAllHosts();

  // Years running: first episode to the year the site was last built — the
  // academy's span, not the catalog's, so it keeps counting past the newest
  // recording. Whole completed years only, and the trailing "+" carries the
  // part-year, so the figure is never rounded up past what's true.
  const firstYear = Number(stats.firstYear);
  const lastYear = Math.max(Number(stats.latestYear) || 0, new Date().getUTCFullYear());
  const yearsRunning = firstYear && lastYear > firstYear ? lastYear - firstYear : 1;

  // The card opens on real episodes — most recent first, and only ones with a
  // summary to reveal, so the expanded state is never a blank panel.
  const cardEpisodes = getAllEpisodes()
    .filter((e) => e.excerpt)
    .slice(0, 3)
    .map((e) => ({
      slug: e.slug,
      title: e.title,
      episodeNumber: e.episodeNumber,
      summary: e.excerpt,
      guest: e.guests[0],
    }));

  return (
    <div className="bento-grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 lg:grid-rows-2">
      {/* Headline tile — slate, spans the full height of the grid */}
      <div
        className="bento-cell relative flex min-h-[400px] flex-col justify-between rounded-2xl border border-white/10 p-9 sm:col-span-2 sm:p-11 lg:col-span-1 lg:row-span-2 lg:min-h-0"
        style={{ background: "var(--gradient-hero)" }}
      >
        <div
          aria-hidden
          className="absolute inset-0 rounded-2xl opacity-25"
          style={{ background: "var(--gradient-hero-glow)" }}
        />
        <div className="relative z-10">
          <p className="text-display font-light tracking-tight text-white">
            <AnimatedStat value={`${stats.count}+`} />
          </p>
          <p className="mt-3 text-body-lg text-white/60">Recorded conversations</p>
        </div>
        <p className="relative z-10 text-h3 font-light tracking-tight text-white">
          The business of eye care,{" "}
          <span className="text-white/45">discussed by the people who run it.</span>
        </p>
      </div>

      <HostsTile hosts={hosts} hostCount={stats.hostCount} className={tileClass} />

      {/* Convening — the number counts the years out; the caption keeps the claim */}
      <div className={tileClass}>
        <div className="flex flex-1 items-center justify-center">
          {/* Baseline-aligned so the unit sits on the figure's line, not its box. */}
          <p className="flex items-baseline gap-2 font-light tracking-tight text-ink-900">
            <span className="text-display">
              <AnimatedStat value={`${yearsRunning}+`} />
            </span>
            <span className="text-h3 text-ink-400">years</span>
          </p>
        </div>
        <p className="mt-6 text-balance text-body-lg text-ink-900">Convening leaders</p>
        <p className="mt-2 text-balance text-body text-ink-400">
          {`A standing conversation since ${stats.firstYear}, not a campaign.`}
        </p>
      </div>

      {/* Every card it opens is ophthalmology */}
      <EpisodeExpandMark
        episodes={cardEpisodes}
        title="100% ophthalmology-specific"
        sub="Built on eye-care realities."
        className={tileClass}
      />
      {/* Blind spots — the field test finds what the practice can't see */}
      <BlindSpotGrid
        title="Blind spots, mapped"
        sub="What a practice can’t see from the inside."
        className={tileClass}
      />

    </div>
  );
}
