/**
 * One-off dev tool (like scripts/scrape/*): rasterizes Natural Earth land polygons
 * into a packed 1-bit equirectangular mask and writes it to
 * src/components/home/landmask.ts, which HeroGlobe uses to place particles over land.
 *
 *   npx tsx scripts/generate-landmask.ts
 *
 * The output is committed. Re-run only to change the resolution or the source data.
 *
 * Resolution note: 512x256 is ~0.7 deg/cell (~78 km at the equator). The globe draws
 * 2000 points over land, which works out to ~270 km spacing, so the mask is comfortably
 * finer than the points it feeds — coastlines stay crisp rather than blocky.
 *
 * Method: even-odd scanline fill, not per-cell point-in-polygon. Testing all 131k cells
 * with d3-geo's spherical geoContains against the 1:50m geometry takes many minutes;
 * intersecting each of the 256 scanlines with the edge list is O(rows x edges) and runs
 * in well under a second. Natural Earth already splits polygons at the antimeridian, so
 * a planar test in lon/lat space is safe here.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";
import type { Topology, GeometryCollection } from "topojson-specification";
import type { FeatureCollection, Position } from "geojson";

const WIDTH = 512;
const HEIGHT = 256;

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, "..", "src", "components", "home", "landmask.ts");

// eslint-disable-next-line @typescript-eslint/no-require-imports
const topology = require("world-atlas/land-50m.json") as Topology<{
  land: GeometryCollection;
}>;
const land = feature(topology, topology.objects.land) as FeatureCollection;

// Flatten every polygon ring into a single edge list.
const edges: [number, number, number, number][] = []; // lon1, lat1, lon2, lat2
function addRing(ring: Position[]) {
  for (let i = 0; i < ring.length - 1; i++) {
    edges.push([ring[i][0], ring[i][1], ring[i + 1][0], ring[i + 1][1]]);
  }
}
for (const f of land.features) {
  const g = f.geometry;
  if (g.type === "Polygon") g.coordinates.forEach(addRing);
  else if (g.type === "MultiPolygon") g.coordinates.forEach((poly) => poly.forEach(addRing));
}

const bytes = new Uint8Array((WIDTH * HEIGHT) / 8);
let hits = 0;

for (let row = 0; row < HEIGHT; row++) {
  // Sample cell centres. Row 0 is the north pole edge, so lat runs 90 -> -90.
  const lat = 90 - ((row + 0.5) / HEIGHT) * 180;

  // Longitudes where this scanline crosses a polygon edge.
  const crossings: number[] = [];
  for (const [lon1, lat1, lon2, lat2] of edges) {
    if (lat1 <= lat === lat2 <= lat) continue; // no crossing (also skips horizontals)
    crossings.push(lon1 + ((lat - lat1) / (lat2 - lat1)) * (lon2 - lon1));
  }
  if (crossings.length < 2) continue;
  crossings.sort((a, b) => a - b);

  // Even-odd: fill between successive pairs.
  for (let i = 0; i + 1 < crossings.length; i += 2) {
    // Cells whose CENTRE falls inside the span, matching the sampling convention.
    const from = Math.max(0, Math.ceil(((crossings[i] + 180) / 360) * WIDTH - 0.5));
    const to = Math.min(WIDTH - 1, Math.floor(((crossings[i + 1] + 180) / 360) * WIDTH - 0.5));
    for (let col = from; col <= to; col++) {
      const index = row * WIDTH + col;
      if ((bytes[index >> 3] >> (7 - (index & 7))) & 1) continue;
      bytes[index >> 3] |= 0b1000_0000 >> (index & 7); // MSB-first within each byte
      hits++;
    }
  }
}

const base64 = Buffer.from(bytes).toString("base64");
const coverage = ((hits / (WIDTH * HEIGHT)) * 100).toFixed(1);

fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/generate-landmask.ts — do not edit by hand.
// Natural Earth 1:50m land polygons (public domain) packed as a 1-bit
// equirectangular mask, MSB-first, row 0 = north pole, column 0 = 180°W.
// ${WIDTH}x${HEIGHT} cells, ${coverage}% land.
export const LANDMASK = {
  w: ${WIDTH},
  h: ${HEIGHT},
  bits: "${base64}",
} as const;
`,
  "utf8",
);

console.log(`wrote ${OUT}`);
console.log(`  ${WIDTH}x${HEIGHT}, ${edges.length} edges, ${hits} land cells (${coverage}%), ${base64.length} b64 chars`);
